# Generated by Django 4.1.5 on 2023-01-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')])),
                ('profileImages', models.ImageField(null=True, upload_to='profileImages/')),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImages/'),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ticketImages', models.ImageField(null=True, upload_to='ticketImages/')),
                ('profileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel')),
            ],
        ),
    ]
