# Generated by Django 4.1.5 on 2023-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_profilemodel_concertmodel_poster_ticketmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت ها'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='lenght',
            field=models.IntegerField(verbose_name='مدت زمان کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImages/', verbose_name='عکس پوستر'),
        ),
    ]
