# Generated by Django 4.1.5 on 2023-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_alter_concertmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='startDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
